### ISSUE TITLE
Python virtual environment not automatically opening in terminal

### ISSUE THREAD

**Issue by LongVanNgo** [getcursor/cursor#1017]
Cursor seems to not activate virtual environments automatically when creating a new terminal.

When i create an environment using ```Python: Create environment...``` and select my interpreter in that environment, VScode enters it automatically when creating new terminal:

![image](https://github.com/getcursor/cursor/assets/35302246/201ee82a-37ec-406f-bdde-ac59e91250d2)

But when I open a new terminal in Cursor it doesn't do it, and even when i change JSON settings it still doesn't activate automatically:

![image](https://github.com/getcursor/cursor/assets/35302246/bfb93f05-7be3-4cc7-8c7a-1d2f036df8e9)

A friend reproduced the issue.

2) Please include the name of your operating system
- Ubuntu 22.04.2 

3) If you can, steps to reproduce are super helpful
- Create environment: ```Python: Create environment...```
- Select interpreter in newly created virtual environment
- Open new terminal

Then in Cursor nothing would happen, in VScode it opens it automatically as intended.

**Comment by jevpham** [comment]
I have the same issue. It seems you just have to activate the virtual environment manually for now.

**Comment by alberduris** [comment]
This is still an issue. Is there any update on this?

**Comment by emilesilvis** [comment]
Yep, same issue.

**Comment by meminens** [comment]
Same issue here. Although Cursor shows my virtual environment in the bottom right, I have to manually activate it in the terminal every time I launch Cursor.

**Comment by abhavk** [comment]
Still! Any fixes planned?

**Comment by Vanekkk1** [comment]
SAME , FIX THIS , it is very annoying

**Comment by a-antoniades** [comment]
same

**Comment by whogben** [comment]
Confirming this issue, choosing "Select Interpreter" and then browsing the filesystem and choosing .venv/bin/python doesn't generate an error, but it doesn't select the interpreter either.

**Comment by peter-stuart-turner** [comment]
Same issue

**Comment by Vanekkk1** [comment]
aaa

**Comment by gbaian10** [comment]
Currently, I have two solutions.
One is to first run `bash` and then execute `zsh` to return to the zsh environment, which can solve my problem for now.
Another method is to use `.devcontainer` for development within a container, which also resolves my issue.

**Comment by danpysmak** [comment]
Please fix this!!!!
Extremely frustrating. Cursor is supposed to be better than VSCode, not otherwise :(

**Comment by gbaian10** [comment]
https://github.com/getcursor/cursor/issues/549#issuecomment-2567104828

This method can resolve the issue I encountered on Linux.

**Comment by msamsami** [comment]
Same issue.

**Comment by Vanekkk1** [comment]
So guys, I figured out when this happened particularly.

When you clone a repo and name the folder in some way and then you create the virtual env there.

If you then change the folder name it no longer picks up the virtual env

Regards,
Ivan Tryskyba

**Comment by msamsami** [comment]
> So guys, I figured out when this happened particularly.
> 
> When you clone a repo and name the folder in some way and then you create the virtual env there.
> 
> If you then change the folder name it no longer picks up the virtual env
> 
> Regards,
> Ivan Tryskyba
> […](#)

Yeah, not exactly! You're right that renaming the folder with the venv can mess things up because of the paths, but the issue we're seeing in Cursor seems to be something else.

**Comment by prashantchaudhary1** [comment]
For me adding this to ~/.zshrc worked:

# Auto-activate virtual environment when in project directory
if [[ -f "venv/bin/activate" ]]; then
    source venv/bin/activate
elif [[ -f ".venv/bin/activate" ]]; then
    source .venv/bin/activate
fi

**Comment by smg-nthuan** [comment]
it's used to work for a while, but after updating from a recent update, it's not working anymore, absolutely annoying

**Comment by CompadreP** [comment]
OMG guys! I mean, this issue is 20 months old, and it's supposed to be one of the basic functionalities IDE should provide! Just switched from PyCharm and find this extremely disappointing!

**Comment by smg-nthuan** [comment]
I've just updated Cursor to version 1.2.1 and the problem is solved

<img width="244" height="387" alt="Image" src="https://github.com/user-attachments/assets/c2b508d1-4c7a-46e3-8aa9-1365b1f3a21c" />

**Comment by nvluxiaoz** [comment]
I updated to the latest version and it does not resolve the issue.

**Comment by jasonp-lnw** [comment]
Not sure how often cursor takes VS Code changes but I was using VS Code up until this week and auto venv worked up until the latest version of VS Code. If they are taking every VS Code update, I'm guessing the issues comes from VS Code itself.

**Comment by sdk451** [comment]
The issue is still there for the latest version of Cursor. It is BY FAR the single most annoying thing about Cursor for python. Wastes immense amount time and causes endless undos and code refactoring as Cursor attempts time after to time to reinstall libraries that are already in the (non-activated) environment, and writes test script after test script.  NEEDS TO BE FIXED.
