### ISSUE TITLE
undo `cmd+z` is weird

### ISSUE THREAD

**Issue by 2nthony** [getcursor/cursor#1781]
using cursor latest version

vscode:
1. select lines of code, and type `asdf`
2. press cmd+z once, it will revert to origin code

cursor:
1. select lines of code, and type `asdf`
2. press cmd+z once, it will become `asd`, **NOT** revert to origin code

it drive me nuts writing code.

**Comment by 2nthony** [comment]
it fixed in v40

**Comment by hybridherbst** [comment]
Still happening on the latest version. This is very annoying!

**Comment by YYYasin19** [comment]
For us it seems to happen when `Cursor Tab` is activated -- the guess is that is seems to save after each keystroke which breaks the `undo`

**Comment by todd-grilliot** [comment]
I came here to post this exact issue. Please fix this! It makes cmd + z so annoying to use!

**Comment by lokeshrana9999** [comment]
+1

**Comment by lokeshrana9999** [comment]
+1

**Comment by jonrosner** [comment]
+1 please fix. This is my most n°1 quality of live problem when using cursor.

**Comment by Smef** [comment]
This is happening to me as well, and makes work very frustrating sometimes. It's one of those things that makes your flow come to a complete stop as you reset your brain to what is going on.

I don't think it's related to a specific file type. I've seen this in every file I've had to undo in. This does seem to be related to Cursor Tab. Turning that off resolves the issue.

**Comment by willbonney** [comment]
+1 this is really jarring coming from vs code

**Comment by SvenMeyer** [comment]
To undo changes you have already accepted in Cursor, you have a couple of options:

Use checkpoints: Every time you generate code using Composer, Cursor creates a checkpoint. You can return to any previous version by clicking on "checkout" near that checkpoint. This is useful if you don't like the current changes and want to revert to an earlier state.

For Composer changes: If you're working in Composer, you can review changes in the diff view and use the provided buttons to accept or reject changes. If you've already accepted changes but want to undo them, you can use the checkpoints feature mentioned above.

For Tab completion: If you've accepted suggestions using Tab completion, you can use standard text editor undo functionality (usually Ctrl+Z or Cmd+Z) to revert the changes.

(source Docs AI on cursor.com)
