### ISSUE TITLE
How to unhide menu bar?

### ISSUE THREAD

**Issue by agn-7** [getcursor/cursor#3007]
Accidentally, the menu bar disappeared, and despite using Toggle Menu Bar via Ctrl + P, it isn't unhided!

![Image](https://github.com/user-attachments/assets/75bfa372-9bf6-4658-9ec8-317f134c40fd)

**Comment by BikashWhitehat** [comment]
same issue in my system as well

**Comment by agn-7** [comment]
I fixed the issue with a plan B solution:

I removed the config folder of the Cursor as follows and initialized it again:

```
cd ~/.config/
rm -rf Cursor
```

**Comment by BikashWhitehat** [comment]
it is still not visible after removing config folder in my case

**Comment by BikashWhitehat** [comment]
> [@BikashWhitehat](https://github.com/BikashWhitehat) did you try with "ctrl + p" then type "Toggle Menu Bar"?

done that as well, doesn't work

**Comment by agn-7** [comment]
No idea, in my case, I deleted the .Appimage file, downloaded that again, removed that config, then in the new run it was fixed, however, all of my settings had been removed

**Comment by Mulubrhan1511** [comment]
Ctrl + Shift + P 
then search for "view toggle menubar" then click that
