### ISSUE TITLE
Weird AI Duplication Glitch

### ISSUE THREAD

**Issue by danperks** [getcursor/cursor#599]
Hard to explain, so I've recorded a video.
When trying to generate changes to existing code, the code begins to duplicate itself and ends up mangled.
Initial generation is fine, as the video shows, but code changes get very messed up.

https://github.com/getcursor/cursor/assets/49082234/0bdb56b3-ade1-4dff-8722-28a886bdcd21

My Version Info:
![image](https://github.com/getcursor/cursor/assets/49082234/805c31c0-a61a-45c9-9a83-82b9b1ac4f0f)

**Comment by truell20** [comment]
Should be fixed in the latest release 🙂

**Comment by JeremiLorenti** [comment]
This is still occurring to me, is there another glitch or fix?
