### ISSUE TITLE
Remote SSH with MacOS host not working. Release link broken.

### ISSUE THREAD

**Issue by jorge-menjivar** [getcursor/cursor#715]
Connecting to any Linux distro from my Fedora workstation with Cursors works well. However, when trying to connect to my Macbook I get the following:

```sh
[Trace  - 02:17:51.187] Server install command stdout:
Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.6.0-1.0.0/vscode-reh-darwin-x64.tar.gz'
Error while extracting server contents
0aa760f5785da1756a8acc88: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/Users/jorge/.cursor-server/.4bc2ab0a56df141f4b33c57498dcf59af5cc5c82.log==
osReleaseId==unknown==
arch==x86_64==
platform==Darwin==
tmpDir==/tmp==
0aa760f5785da1756a8acc88: end
```

It seems that the link to download the server is broken. The `vscode-server.tar.gz` instead has the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:26ea4003-701e-0009-4e43-c72677000000
Time:2023-08-05T02:17:51.0661217Z</Message></Error>%    
```

In contrast when downloading on Linux through `https://cursor.blob.core.windows.net/remote-releases/0.6.0-1.0.0/vscode-reh-linux-x64.tar.gz` the actual tarball is downloaded.

**Comment by tmm1** [comment]
This issue is fixed in today's 0.41.1 release.

**Comment by notoriousturtle** [comment]
This is still an issue in 0.41.2.

https://cursor.blob.core.windows.net/remote-releases/<random-sha1>/vscode-reh-darwin.tar.gz

**Comment by tmm1** [comment]
Are you connecting to an Intel Mac?

**Comment by notoriousturtle** [comment]
M3 local to Intel Mac client side.

**Comment by tmm1** [comment]
Got it. I only tested with M1 remote. Can you try again now?

**Comment by 1Muggle** [comment]
Remote ssh connection to Windows 10 via Cursor version 0.41.2 still doesn't work on Macbook M1

My cursor info
```
Version: 0.41.2
VSCode Version: 1.91.1
Commit: 297991d169fa3a11975c5aa95adc69be73250c70
Date: 2024-09-21T04:18:39.370Z
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 24.0.0
```

Remote - SSH output
```
...
[10:20:24.473] Got request to download on client for {"artifact":"cli-win32-x64","destPath":"C:\\Users\\noah\\.cursor-server/vscode-cli-297991d169fa3a11975c5aa95adc69be73250c70.zip"}
[10:20:24.473] server download URL: https://cursor.blob.core.windows.net/remote-releases/297991d169fa3a11975c5aa95adc69be73250c70/cli-win32-x64.tar.gz
[10:20:24.473] Downloading VS Code server locally...
[10:20:25.462] Terminating local server
[10:20:25.468] Resolver error: Error: Failed to download VS Code Server (Server returned 404)
...
```
