### ISSUE TITLE
Keyboard Shortcut to Close Chat Window

### ISSUE THREAD

**Issue by gordbegli** [getcursor/cursor#860]
**Is your feature request related to a problem? Please describe.**
It's annoying when I have to use my mouse to close the chat window.

**Describe the solution you'd like**
I would like a keyboard shortcut to close the chat window. I work on a mac and sometimes want the extra viewing space when not reading the chat output.

**Comment by sualehasif** [comment]
we have a short, (cmd+option+b on mac). this is obscure :(:( and we will try to fix this.

**Comment by josephecombs** [comment]
You can "SHIFT + TAB" three times from the focused chat window (this will not be visible in the UI, just trust me) to change the focus of the application. Then press "Enter". This closes the chat window.

**Comment by jakobFNF** [comment]
There's still another issue: this keyboard shortcut doesn't work when you're focused on a chat input field. We will try to address this more effectively. I'll close this issue for now because the initial problem has been resolved.

**Comment by Evidlo** [comment]
When the chat input field is selected, `Cmd + Option + b` (on Linux `Ctrl + Alt + b`) doesn't work.  I need to press `Esc` to defocus the chat input field.

Is this behavior intentional?

**Comment by Evidlo** [comment]
> There's still another issue: this keyboard shortcut doesn't work when you're focused on a chat input field.

@jakobFNF Has an issue been filed for this yet?  Still present in v0.45.11

**Comment by Den-MM** [comment]
Binding the aichat.newchataction in the keybindings made it work for me.
When it doesn't interfere with other shortcuts.
