### ISSUE TITLE
code 

### ISSUE THREAD

**Issue by TubbyStubby** [getcursor/cursor#864]
```
➜ cursor --version
0.9.3
e83fb25fe9144aa8b230e6f9ee2056e20fb24c70
x64
```

OS: Windows 11

I installed cursor few days ago. And during installation I was give 2 options, install `code` or `cursor` command. I chose `cursor`, and it works fine. But I just noticed that when I use `code .` it opens cursor which is not what I was expecting.

**Comment by sualehasif** [comment]
seems like a super annoying bug. really sorry for causing this. will investigate soon if this is a bug on our side. (cc: @Sanger2000) if this is, will release a hot fix!

**Comment by GitMurf** [comment]
same issue for me. this is very upsetting. vscode is still my main IDE and I installed cursor to try it out for a while to see if maybe I would replace vscode down the road. I am uninstalling cursor because of this.

**Comment by AlxndrJhn** [comment]
I am also looking for a fix, I am deleting
```powershell
remove-item c:\Users\jahna\AppData\Local\Programs\cursor\resources\app\bin\code.cmd
remove-item c:\Users\jahna\AppData\Local\Programs\cursor\resources\app\bin\code
```
after every update

I accepted the `code` replacement, but can't find the setting, I would like to deactivate this feature

**Comment by Souvik-Cyclic** [comment]
This issue is still not fixed. @sualehasif

**Comment by twirlse** [comment]
I fixed this issue by uninstalling Cursor :) Not really acceptable behavior to hijack other programs, IMHO.

**Comment by vchrombie** [comment]
Faced this issue on Mac OS. The cursor application overrides the `code` command and the only way to revert this is delete the `code` script (`rm /usr/local/bin/code`) and install 'code' command in PATH.

Alternatively you can edit the `code` script (`nano /usr/local/bin/code`).

```diff
-	REMOTE_CLI="$(which -a 'cursor' | grep /remote-cli/)"
+	REMOTE_CLI="$(which -a 'code' | grep /remote-cli/)"


- ELECTRON="$CONTENTS/MacOS/Cursor"
+ ELECTRON="$CONTENTS/MacOS/Electron"
```

This way, `cursor` would run cursor application and `code` runs vs code.

**Comment by AhmedAlharees** [comment]
The issues is still present till this day, I hope the team fix it soon, it's small but very annoying.

**Comment by aady01** [comment]
If you’re in Windows, go to %localappdata%\Programs\cursor\resources\app\bin and delete 2 files:
code
code.cmd
I hope this helped.

**Comment by BurakKTopal** [comment]
@aady01, after removing these files, `cursor .` didn't work for me anymore.

I fixed it by adding the following alias to my `.bashrc` shell config file:

`alias cursor='"C:\Users\<username>\AppData\Local\Programs\cursor\resources\app\bin\cursor"'`

As a result `cursor .` launches cursor, while `code .` launches vscode as intended.

**Comment by jcache** [comment]
FYI - I followed the suggestions above on my windows computer, deleting the 2 files:
>%localappdata%\Programs\cursor\resources\app\bin\code
> %localappdata%\Programs\cursor\resources\app\bin\code.cmd

I've been using both commands for about a month, and somehow it reset itself in the last week. So I'm having to delete it again.
It would be great if there were a permenant fix.

**Comment by ulysses-ck** [comment]
I agree in that installing first VSC before cursor did resolve it. Then when I have a Windows fresh installation, and installing cursor, pressing only install cursor command, then code command is registering

**Comment by JeanHz123** [comment]
Hello, I am not an English speaker but I hope you understand me:
When you install the editor it gives you these options:

![Image](https://github.com/user-attachments/assets/e6b23e22-c138-45ea-a090-45c3e6eb509b)

> By installing only the first one, what it does is that it somehow replaces the "code" of the vscode command line registered in the path with "cursor", which means that when you use "cursor" it opens Cursor and when you want to use "code" it no longer opens vscode because I delete it in the path

> When you install only the second one, what it does is that it adds you to your command line and registers the "cursor" in the path (it does not affect the "code" of vscode), that is, you have "code" to open vsco and "cursor" to open Cursor, both separately

**To solve this there are several ways (if you installed both options) and you want to have the "**code**" and "**cursor**" separately:**
1. Within Cursor you can do **Ctrl+Shift+P** and there search for "**Shell Command: uninstall 'code' command from path**" and click on that option (but it is not there somehow in the path the two are still kept registered)
2. Go to your environment variable (path) and delete "**c:\Users\[Your User Name]\AppData\Local\Programs\cursor\resources\app\bin**" (you will see two, just delete one) and add the command line for VScode "**C:\Program Files\Microsoft VS Code\bin**" and that should be it.

**The other way is to uninstall Cursor completely**

1. Uninstall Cursor.
2. You delete these folders "**C:\Users\TU_USER\AppData\Roaming\Cursor" and "C:\Users\TU_USUARIO\.cursor**" within the PATH you delete this "**c:\Users\TU_USER\AppData\Local\Programs\cursor\resources\app\bin**"
3. You install Cursor again and it should show you the entire installation process

**Comment by bipboop1** [comment]
This issue is still not resolved, soon to be two years later.

**Comment by JeanHz123** [comment]
That is what it says, that when you install Cursor and install its command line it eliminates the vscode path and deletes it in the ENVIRONMENT VARIABLE, that is why it is only necessary to choose the cursor (when it is a clean installation) and now for your case it seems that you installed vscode for the system and for your current user (which would not be a good option if you are the only one who uses your computer and also that you will have not very extensive problems in the path but there are some), now what you just did should solve your problem because you reset the vscode path in the environment variable (which at the time Cursor deleted it) now if what you want is to have `code` for VSCODE and `cursor` for CURSOR, it would be that you follow the steps that I left you

**Comment by devtooligan** [comment]
I'm on Mac. Tried some of the solutions here and didn't work. What worked for me was:

1. Delete the current script: sudo rm /usr/local/bin/code
2. Open VS Code (you'll need to find it in your Applications folder)
3. Open the Command Palette (Cmd+Shift+P)
4. Type and select "Shell Command: Install 'code' command in PATH"

**Comment by tantan39** [comment]
On the Mac. Open the Command Palette (Cmd+Shift+P), type 'shell command', and run the Shell Command: Install 'code' command in PATH command.

Then VS Code would override it.

**Comment by Yawhou** [comment]
> This issue is still not resolved, nearly two years later.
> 
> For me, the fix was: The VS Code 'code' command was only in the User PATH, while the cursor 'code' command was both in the User and System PATH. I used win + R to launch 'sysdm.cpl', and opened Environment Variables (under the 'Advanced' tab). From there, I copied the VS Code path from user PATH to the System PATH. The VS Code command then took priority over Cursor's. I guess this would persist across Cursor updates? Not sure.

Thanks, this works for me. 
Oh and for my windows machine, the path for vscode needs to be moved up to higher than cursor's path for it to work.
At least for now, I can use `code` `code .` to open vscode and `cursor` `cursor .` to open cursor.

**Comment by vesnikos** [comment]
Is this what we call `aggresive` marketing? I thought i would start with cursor, and i was really suprised to see it launching instead of my traditional well-known vsc

**Comment by derciojds** [comment]
> Is this what we call `aggresive` marketing? I thought i would start with cursor, and i was really suprised to see it launching instead of my traditional well-known vsc

I don't even consider it a marketing strategy, it's unethical such thing is considered a dark pattern UX, also known as deceptive design pattern.

**Comment by chrispmcgee** [comment]
> This issue is still not resolved, nearly two years later.
> 
> For me, the fix was: The VS Code 'code' command was only in the User PATH, while the cursor 'code' command was both in the User and System PATH. I used win + R to launch 'sysdm.cpl', and opened Environment Variables (under the 'Advanced' tab). From there, I copied the VS Code path from user PATH to the System PATH. The VS Code command then took priority over Cursor's. I guess this would persist across Cursor updates? Not sure.

This is my solution for now. Thank you, @bipboop1. I also agree with @derciojds. A bug that has lasted for two years? Nope, it's intentional.

**Comment by erbanku** [comment]
I am here to say some very nasty words, it is very annoying and disgusting to automatically register `cursor` as `code` after every update or in the random period, as I said many times `NO` in the cursor settings / by deleting the `code`,`code.cmd` file from the `C:\Users\USERNAME\AppData\Local\Programs\cursor\resources\app\bin` and changing the priority in environment variables. It is a very aggressive and unethical strategy, but you guys chose to keep doing this, for the issue has been open for nearly 2 years.

**Comment by 411A** [comment]
Same issue. Even removing code from the cursor path and reinstalling VSCode didn't overwrite it.

**Comment by shahzaib3120** [comment]
If you're encountering issues with the `code` command opening the cursor, try running

`where code` on Windows 

or 

`which code` on Linux. You might see paths like:

```
C:\Users\<username>\AppData\Local\Programs\cursor\resources\app\bin\code  
C:\Users\<username>\AppData\Local\Programs\cursor\resources\app\bin\code.cmd  
C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin\code  
C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd  
```

or their equivalents on Linux.

In my case, removing the entries under the `cursor\resources\app\bin\` directory resolved the issue. It seems like those were taking precedence over the official VS Code paths.

Hope this helps!

**Comment by LuckyCurve** [comment]
try to delete os path item that contains cursor but not working, now I decide to uninstall cursor to fix it.

**Comment by erbanku** [comment]
The method mentioned above does work, but previously, even after doing that, cursor updates would still change the user configuration. However, this hasn't happened in the most recent updates, probably because the development team felt the users' anger, LOL.

**Comment by hsinghal11** [comment]
This worked for me, so why not for you "https://stackoverflow.com/questions/79616295/the-code-command-opens-cursor-instead-of-vs-code"

**Comment by tonegabes** [comment]
> If you’re in Windows, go to %localappdata%\Programs\cursor\resources\app\bin and delete 2 files: code code.cmd I hope this helped.

Thank you. This worked for me.

**Comment by Chipsnet** [comment]
The core of this issue is that every time Cursor updates, it replaces the code command.
Even if I manually delete the code command from
%LOCALAPPDATA%\Programs\cursor\resources\app\bin,
the next update puts it back again.

This is incredibly frustrating. Cursor should not overwrite the code command against the user’s wishes.

I’m fairly certain the Cursor team could fix this in about 30 minutes, so I’m puzzled why it still hasn’t been addressed.

**Comment by vesnikos** [comment]
you can use `cursor` cmd to open cursor. just saying... 🙄

**Comment by aady01** [comment]
> you can use `cursor` cmd to open cursor. just saying... 🙄

yeah i guess because this issue is fixed now.

**Comment by F1LT3R** [comment]
> The core of this issue is that every time Cursor updates, it replaces the code command. Even if I manually delete the code command from %LOCALAPPDATA%\Programs\cursor\resources\app\bin, the next update puts it back again.
> 
> This is incredibly frustrating. Cursor should not overwrite the code command against the user’s wishes.
> 
> I’m fairly certain the Cursor team could fix this in about 30 minutes, so I’m puzzled why it still hasn’t been addressed.

Exactly. 

Cursor updates still blow away `code` for me.

Let's see if we can keep this bug open for just one more year.

Once we're reached the 3 year mark on this bug, it should be ready for someone to start fixing.
