### ISSUE TITLE
Bug: Cursor is not launching through `cusrsor .` or `code .` command in WSL2 Distro ubuntu.

### ISSUE THREAD

**Issue by startup-dreamer** [getcursor/cursor#870]
I am trying to launch cursor through WSL ubuntu but there is some error related to .cursor-server file 
screenshots:
![image](https://github.com/getcursor/cursor/assets/106421807/c59f9a3d-891e-42cb-b1ec-57ec877735b7)
![image](https://github.com/getcursor/cursor/assets/106421807/d4f33c59-0f86-469e-b041-acb873f9d19f)
![image](https://github.com/getcursor/cursor/assets/106421807/9e467a96-fa78-4edb-83bb-20da14edc53f)
![image](https://github.com/getcursor/cursor/assets/106421807/6a972568-c5bf-40e5-820b-ac20c619ec27)

**Comment by Umar-Azam** [comment]
Have the same issue on my end.

**Comment by truell20** [comment]
Yep, this is expected atm. We will look into fixing as soon as we can.

**Comment by startup-dreamer** [comment]
@truell20 please close this issue as soon as it is fixed so that I will be able to use cursor again with WSL

**Comment by worldofgeese** [comment]
Just to add to this issue, I see a different sort of error when attempting to run `cursor` in Ubuntu on WSL2:

```console
ursor
To use Cursor with the Windows Subsystem for Linux, please install Cursor in Windows and uninstall the Linux version in WSL. You can then use the `cursor` command in a WSL terminal just as you would in a normal command prompt.
Do you want to continue anyway? [y/N] y
To no longer see this prompt, start Cursor with the environment variable DONT_PROMPT_WSL_INSTALL defined.
/mnt/c/Users/taoha/AppData/Local/Programs/cursor/resources/app/bin/cursor: 62: /mnt/c/Users/taoha/AppData/Local/Programs/cursor/resources/app/bin/../cursor: not found
```

**Comment by Jacksonmills** [comment]
> Just to add to this issue, I see a different sort of error when attempting to run `cursor` in Ubuntu on WSL2:
> 
> ```
> ursor
> To use Cursor with the Windows Subsystem for Linux, please install Cursor in Windows and uninstall the Linux version in WSL. You can then use the `cursor` command in a WSL terminal just as you would in a normal command prompt.
> Do you want to continue anyway? [y/N] y
> To no longer see this prompt, start Cursor with the environment variable DONT_PROMPT_WSL_INSTALL defined.
> /mnt/c/Users/taoha/AppData/Local/Programs/cursor/resources/app/bin/cursor: 62: /mnt/c/Users/taoha/AppData/Local/Programs/cursor/resources/app/bin/../cursor: not found
> ```

Same thing here! Also noticed it broke my `code .` command as well ... luckily I can just open Cursor and go on my way, watching this for updates 🫡

**Comment by Jacksonmills** [comment]
Any updates on this? Still broken for me

**Comment by lesmo** [comment]
It's unbelievable this is still broken after so many months, and the fix is rather simple. Sadly Cursor is not open source... but here's a quick workaround based on VS Code's current launcher from WSL:

> [!CAUTION]
> This will most likely break after Cursor gets an update. Hopefully they'll fix this in the next update, but if not these tweaks may need to be done again after every update.

> [!NOTE]
> You should install the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) before attempting these steps

> [!IMPORTANT]
> I opened a WSL folder at least once before doing these steps, which installed Cursor's WSL Server in `~/.cursor-server/bin`. I'm not sure if this altered VS Code script would trigger that too if you directly run `cursor` without the WSL Server installed.

1. Open the `cursor` linux script
   - Most likely located at `C:\Users\<your user>\AppData\Local\Programs\cursor\resources\app\bin\`
   - If you've installed the `cursor` command you can also:
   		- Use `which` in WSL:
   		  ```console
   	      $ which cursor
   	      /mnt/c/Users/lesmo/AppData/Local/Programs/cursor/resources/app/bin/cursor
   		  ```
   		- Use `where` in Windows' Command Prompt:
   		  ```console
   		  > where cursor
   		  c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor
   		  c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor.cmd
   		  ```
   		- Use `(Get-Command cursor).Source` in PowerShell :
   		  ```console
   		  > (Get-Command code).Source
		  C:\Users\lesmo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
   		  ```
2. Copy the `code` linux script contents into the `cursor` one
	- Most likely located at `C:\Users\<your user>\AppData\Local\Programs\Microsoft VS Code\bin\`
3. Patch the script with:
	- Cursor values for the variables:
		- `COMMIT` should have the value of the binary under `~/.cursor-server/bin`, which for me right now is `56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10`
		- `APP_NAME` should be `"cursor"`
		- `NAME` should be `"Cursor"`
		- `SERVERDATAFOLDER` should be `".cursor-server"`
		- `VSCODE_PATH` should be `"$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"`
			- _Paths slightly differ from VS Code, so this extra `dirname` calls are necessary)_
	- Fix the semi-invalid output from the call to Cursor as CLI in line 47
		- The `cat /tmp/remote-wsl-loc.txt` expects to only output a path, but it outputs 2 lines that breaks the script. To fix this, we forcibly get only the 2nd line:
		  ```bash
          WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
		  ```

Cursor will now be correctly launched by whatever WSL instance invokes it. This is my current `cursor` file contents:

```bash
#!/usr/bin/env sh
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
if [ "$VSCODE_WSL_DEBUG_INFO" = true ]; then
	set -x
fi

COMMIT="56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10"
APP_NAME="cursor"
QUALITY="stable"
NAME="Cursor"
SERVERDATAFOLDER=".cursor-server"
VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$VSCODE_PATH/$NAME.exe"

IN_WSL=false
if [ -n "$WSL_DISTRO_NAME" ]; then
	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
	IN_WSL=true
else
	WSL_BUILD=$(uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft.*|.*/\1/')
	if [ -n "$WSL_BUILD" ]; then
		if [ "$WSL_BUILD" -ge 17063 ]; then
			# WSLPATH is available since WSL build 17046
			# WSLENV is available since WSL build 17063
			IN_WSL=true
		else
			# If running under older WSL, don't pass cli.js to Electron as
			# environment vars cannot be transferred from WSL to Windows
			# See: https://github.com/microsoft/BashOnWindows/issues/1363
			#      https://github.com/microsoft/BashOnWindows/issues/1494
			"$ELECTRON" "$@"
			exit $?
		fi
	fi
fi
if [ $IN_WSL = true ]; then

	export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
	CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")

	# use the Remote WSL extension if installed
	WSL_EXT_ID="ms-vscode-remote.remote-wsl"

	ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID >/tmp/remote-wsl-loc.txt 2>/dev/null </dev/null
	WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)

	if [ -n "$WSL_EXT_WLOC" ]; then
		# replace \r\n with \n in WSL_EXT_WLOC
		WSL_CODE=$(wslpath -u "${WSL_EXT_WLOC%%[[:cntrl:]]}")/scripts/wslCode.sh
		"$WSL_CODE" "$COMMIT" "$QUALITY" "$ELECTRON" "$APP_NAME" "$SERVERDATAFOLDER" "$@"
		exit $?
	fi

elif [ -x "$(command -v cygpath)" ]; then
	CLI=$(cygpath -m "$VSCODE_PATH/resources/app/out/cli.js")
else
	CLI="$VSCODE_PATH/resources/app/out/cli.js"
fi
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
exit $?
```

**Comment by vincentsch** [comment]
Also see issue #807

**Comment by ovived** [comment]
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|13.107.213.40|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-14 15:13:18 ERROR 404: Not Found.

ERROR: Failed to download https://update.code.visualstudio.com/commit:56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10-1710443218/server-linux-x64/stable to /root/.cursor-server/bin/56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10-1710443218-1710443598.tar.gz


i get this error 

> It's unbelievable this is still broken after so many months, and the fix is rather simple. Sadly Cursor is not open source... but here's a quick workaround based on VS Code's current launcher from WSL:
> 
> Caution
> 
> This will most likely break after Cursor gets an update. Hopefully they'll fix this in the next update, but if not these tweaks may need to be done again after every update.
> 
> Note
> 
> You should install the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) before attempting these steps
> 
> Important
> 
> I opened a WSL folder at least once before doing these steps. Doing so installed Cursor's WSL Server in `~/.cursor-server/bin`. I'm not sure if this altered VS Code script would trigger that too if you directly run `cursor` without the WSL Server installed.
> 
> 1. Open the `cursor` linux script
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\cursor\resources\app\bin\`
>    * If you've installed the `cursor` command you can also:
>      
>      * Use `which` in WSL:
>        ```
>        $ which cursor
>        /mnt/c/Users/lesmo/AppData/Local/Programs/cursor/resources/app/bin/cursor
>        ```
>      * Use `where` in Windows' Command Prompt:
>        ```
>        > where cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor.cmd
>        ```
>      * Use `(Get-Command cursor).Source` in PowerShell :
>        ```
>        > (Get-Command code).Source
>        C:\Users\lesmo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
>        ```
> 2. Copy the `code` linux script contents into the `cursor` one
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\Microsoft VS Code\bin\`
> 3. Patch the script with:
>    
>    * Cursor values for the variables:
>      
>      * `COMMIT` should have the value of the binary under `~/.cursor-server/bin`, which for me right now is `56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10`
>      * `APP_NAME` should be `"cursor"`
>      * `NAME` should be `"Cursor"`
>      * `SERVERDATAFOLDER` should be `".cursor-server"`
>      * `VSCODE_PATH` should be `"$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"`
>        
>        * _Paths slightly differ from VS Code, so this extra `dirname` calls are necessary)_
>    * Fix the semi-invalid output from the call to Cursor as CLI in line 47
>      
>      * The `cat /tmp/remote-wsl-loc.txt` expects to only output a path, but it outputs 2 lines that breaks the script. To fix this, we forcibly get only the 2nd line:
>        ```shell
>        WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
>        ```
> 
> Cursor will now be correctly launched by whatever WSL instance invokes it:
> 
>  20240219_014531.mp4 
> This is my current `cursor` file contents:
> 
> ```shell
> #!/usr/bin/env sh
> #
> # Copyright (c) Microsoft Corporation. All rights reserved.
> # Licensed under the MIT License. See License.txt in the project root for license information.
> if [ "$VSCODE_WSL_DEBUG_INFO" = true ]; then
> 	set -x
> fi
> 
> COMMIT="56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10"
> APP_NAME="cursor"
> QUALITY="stable"
> NAME="Cursor"
> SERVERDATAFOLDER=".cursor-server"
> VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
> ELECTRON="$VSCODE_PATH/$NAME.exe"
> 
> IN_WSL=false
> if [ -n "$WSL_DISTRO_NAME" ]; then
> 	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
> 	IN_WSL=true
> else
> 	WSL_BUILD=$(uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft.*|.*/\1/')
> 	if [ -n "$WSL_BUILD" ]; then
> 		if [ "$WSL_BUILD" -ge 17063 ]; then
> 			# WSLPATH is available since WSL build 17046
> 			# WSLENV is available since WSL build 17063
> 			IN_WSL=true
> 		else
> 			# If running under older WSL, don't pass cli.js to Electron as
> 			# environment vars cannot be transferred from WSL to Windows
> 			# See: https://github.com/microsoft/BashOnWindows/issues/1363
> 			#      https://github.com/microsoft/BashOnWindows/issues/1494
> 			"$ELECTRON" "$@"
> 			exit $?
> 		fi
> 	fi
> fi
> if [ $IN_WSL = true ]; then
> 
> 	export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
> 	CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> 
> 	# use the Remote WSL extension if installed
> 	WSL_EXT_ID="ms-vscode-remote.remote-wsl"
> 
> 	ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID >/tmp/remote-wsl-loc.txt 2>/dev/null </dev/null
> 	WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
> 
> 	if [ -n "$WSL_EXT_WLOC" ]; then
> 		# replace \r\n with \n in WSL_EXT_WLOC
> 		WSL_CODE=$(wslpath -u "${WSL_EXT_WLOC%%[[:cntrl:]]}")/scripts/wslCode.sh
> 		"$WSL_CODE" "$COMMIT" "$QUALITY" "$ELECTRON" "$APP_NAME" "$SERVERDATAFOLDER" "$@"
> 		exit $?
> 	fi
> 
> elif [ -x "$(command -v cygpath)" ]; then
> 	CLI=$(cygpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> else
> 	CLI="$VSCODE_PATH/resources/app/out/cli.js"
> fi
> ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
> exit $?
> ```
> 
> P.S.: Cursor ppl, hire me? lol

**Comment by stevenobird** [comment]
> * at /tmp/remote-wsl-loc.txt

I've written a small shell script that does the same thing:

```shell
#!/usr/bin/env bash

CODE_WIN_PATH="$(which code)"
CURSOR_WIN_PATH="$(which cursor)"

# overwrite cursor script with the vscode one
cp "$CODE_WIN_PATH" "$CURSOR_WIN_PATH"

# replace vscode vars and paths with cursor ones
# APP_NAME should not be replaced, since remote-cli still gets downloaded as "code" executable
#sed -i 's|APP_NAME="code"|APP_NAME="cursor"|' $CURSOR_WIN_PATH
sed -i 's|NAME="Code"|NAME="Cursor"|' $CURSOR_WIN_PATH
sed -i 's|SERVERDATAFOLDER=".vscode-server"|SERVERDATAFOLDER=".cursor-server"|' $CURSOR_WIN_PATH
sed -i -E 's|VSCODE_PATH=".+"|VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"|' $CURSOR_WIN_PATH

# fix output from the Cursor in CLI
sed -i -E 's|WSL_EXT_WLOC=(.+)|WSL_EXT_WLOC=$(tail -1 /tmp/remote-wsl-loc.txt)|' $CURSOR_WIN_PATH
```

I'm not 100% sure about the `APP_NAME` replacement, but it only worked flawlessly for me when I left it as `code`, since the remote-cli that gets downloaded is still named "code" - at least for me.

**Comment by Fitmavincent** [comment]
I hate to say, but uninstall Cursor is the simplest solution

**Comment by dihak** [comment]
You can try this solution:

1. Open cursor, and CTRL + SHIFT + P, connect to WSL
2. Then in wsl run this `fixWsl.sh`

```
#!/usr/bin/env bash

if [ -e /mnt/c/Users/me/AppData/Local/Programs/cursor/resources/app/bin/code ]; then
    mv /mnt/c/Users/me/AppData/Local/Programs/cursor/resources/app/bin/code /mnt/c/Users/me/AppData/Local/Programs/cursor/resources/app/bin/code.bak
fi

CODE_WIN_PATH="$(which code)"
CURSOR_WIN_PATH="$(which cursor)"
BIN_PATH=$(ls -d ~/.cursor-server/bin/*/ 2>/dev/null | head -n 1)

# overwrite cursor script with the vscode one
cp "$CODE_WIN_PATH" "$CURSOR_WIN_PATH"
if [ ! -e $CURSOR_WIN_PATH.bak ]; then
  cp "$CURSOR_WIN_PATH" "$CURSOR_WIN_PATH.bak"
fi

# replace vscode vars and paths with cursor ones
# APP_NAME should not be replaced, since .cursor-server remote-cli still gets downloaded and extracted as "code" executable
sed -i 's|APP_NAME="code"|NAME="cursor"|' $CURSOR_WIN_PATH
if [ -n "$BIN_PATH" ]; then
  COMMIT=$(basename "$BIN_PATH")
  sed -i "s|COMMIT=\"[^\"]*\"|COMMIT=\"$COMMIT\"|" "$CURSOR_WIN_PATH"
fi
sed -i 's|NAME="Code"|NAME="Cursor"|' $CURSOR_WIN_PATH
sed -i 's|SERVERDATAFOLDER=".vscode-server"|SERVERDATAFOLDER=".cursor-server"|' $CURSOR_WIN_PATH
sed -i -E 's|VSCODE_PATH=".+"|VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"|' $CURSOR_WIN_PATH

# fix output from the Cursor in CLI
sed -i -E 's|WSL_EXT_WLOC=(.+)|WSL_EXT_WLOC=$(tail -1 /tmp/remote-wsl-loc.txt)|' $CURSOR_WIN_PATH
```

**Comment by AhmedMustafa2201** [comment]
> It's unbelievable this is still broken after so many months, and the fix is rather simple. Sadly Cursor is not open source... but here's a quick workaround based on VS Code's current launcher from WSL:
> 
> Caution
> 
> This will most likely break after Cursor gets an update. Hopefully they'll fix this in the next update, but if not these tweaks may need to be done again after every update.
> 
> Note
> 
> You should install the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) before attempting these steps
> 
> Important
> 
> I opened a WSL folder at least once before doing these steps. Doing so installed Cursor's WSL Server in `~/.cursor-server/bin`. I'm not sure if this altered VS Code script would trigger that too if you directly run `cursor` without the WSL Server installed.
> 
> 1. Open the `cursor` linux script
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\cursor\resources\app\bin\`
>    * If you've installed the `cursor` command you can also:
>      
>      * Use `which` in WSL:
>        ```
>        $ which cursor
>        /mnt/c/Users/lesmo/AppData/Local/Programs/cursor/resources/app/bin/cursor
>        ```
>      * Use `where` in Windows' Command Prompt:
>        ```
>        > where cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor.cmd
>        ```
>      * Use `(Get-Command cursor).Source` in PowerShell :
>        ```
>        > (Get-Command code).Source
>        C:\Users\lesmo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
>        ```
> 2. Copy the `code` linux script contents into the `cursor` one
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\Microsoft VS Code\bin\`
> 3. Patch the script with:
>    
>    * Cursor values for the variables:
>      
>      * `COMMIT` should have the value of the binary under `~/.cursor-server/bin`, which for me right now is `56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10`
>      * `APP_NAME` should be `"cursor"`
>      * `NAME` should be `"Cursor"`
>      * `SERVERDATAFOLDER` should be `".cursor-server"`
>      * `VSCODE_PATH` should be `"$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"`
>        
>        * _Paths slightly differ from VS Code, so this extra `dirname` calls are necessary)_
>    * Fix the semi-invalid output from the call to Cursor as CLI in line 47
>      
>      * The `cat /tmp/remote-wsl-loc.txt` expects to only output a path, but it outputs 2 lines that breaks the script. To fix this, we forcibly get only the 2nd line:
>        ```shell
>        WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
>        ```
> 
> Cursor will now be correctly launched by whatever WSL instance invokes it:
> 
>  20240219_014531.mp4 
> This is my current `cursor` file contents:
> 
> ```shell
> #!/usr/bin/env sh
> #
> # Copyright (c) Microsoft Corporation. All rights reserved.
> # Licensed under the MIT License. See License.txt in the project root for license information.
> if [ "$VSCODE_WSL_DEBUG_INFO" = true ]; then
> 	set -x
> fi
> 
> COMMIT="56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10"
> APP_NAME="cursor"
> QUALITY="stable"
> NAME="Cursor"
> SERVERDATAFOLDER=".cursor-server"
> VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
> ELECTRON="$VSCODE_PATH/$NAME.exe"
> 
> IN_WSL=false
> if [ -n "$WSL_DISTRO_NAME" ]; then
> 	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
> 	IN_WSL=true
> else
> 	WSL_BUILD=$(uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft.*|.*/\1/')
> 	if [ -n "$WSL_BUILD" ]; then
> 		if [ "$WSL_BUILD" -ge 17063 ]; then
> 			# WSLPATH is available since WSL build 17046
> 			# WSLENV is available since WSL build 17063
> 			IN_WSL=true
> 		else
> 			# If running under older WSL, don't pass cli.js to Electron as
> 			# environment vars cannot be transferred from WSL to Windows
> 			# See: https://github.com/microsoft/BashOnWindows/issues/1363
> 			#      https://github.com/microsoft/BashOnWindows/issues/1494
> 			"$ELECTRON" "$@"
> 			exit $?
> 		fi
> 	fi
> fi
> if [ $IN_WSL = true ]; then
> 
> 	export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
> 	CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> 
> 	# use the Remote WSL extension if installed
> 	WSL_EXT_ID="ms-vscode-remote.remote-wsl"
> 
> 	ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID >/tmp/remote-wsl-loc.txt 2>/dev/null </dev/null
> 	WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
> 
> 	if [ -n "$WSL_EXT_WLOC" ]; then
> 		# replace \r\n with \n in WSL_EXT_WLOC
> 		WSL_CODE=$(wslpath -u "${WSL_EXT_WLOC%%[[:cntrl:]]}")/scripts/wslCode.sh
> 		"$WSL_CODE" "$COMMIT" "$QUALITY" "$ELECTRON" "$APP_NAME" "$SERVERDATAFOLDER" "$@"
> 		exit $?
> 	fi
> 
> elif [ -x "$(command -v cygpath)" ]; then
> 	CLI=$(cygpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> else
> 	CLI="$VSCODE_PATH/resources/app/out/cli.js"
> fi
> ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
> exit $?
> ```
> 
> P.S.: Cursor ppl, hire me? lol


@lesmo i think it's not a solution. each time the `wsl` restarted, it'll do the update and removal as following
```bash
Updating VS Code Server to version 863d2581ecda6849923a2118d93a088b0745d9d6
Removing previous installation...
Installing VS Code Server for x64 (863d2581ecda6849923a2118d93a088b0745d9d6)
Downloading: 100%
Unpacking: 100%
```

**Comment by KadirBalku** [comment]
My Solution was as follows now everything works as it should for me.

First i uninstalled cursor, removed all folders related with cursor in: 
- `C:/Users/<your user>/AppData/Local/Programs/`
- `C:/Users/<your user>/AppData/Local/`
- `C:/Users/<your user>/AppData/LocalLow/`
- `C:/Users/<your user>/AppData/Roaming/`

and removed the folders:
- `C:/Users/<your user>/.cursor/`
- `C:/Users/<your user>/.cursor-tutor/`

repaired my PATH variable in my WSL Terminal (i am using Arch but should be same in Ubuntu):
- copied my current with `printenv PATH USER` into a text editor
- deleted everything related with cursor (somehow the SHELL Command: Fix WSL install command adds the same PATH twice)
- kept it in the editor for the next steps
- copied the repaired version and in a WSL terminal repaired my PATH variable as follows `PATH="<copied repaired version>"` for me its was important to use "" because some PATH had whitespace
- code command was working again at this point

Deleted the WSL folder `~/.cursor-server`.

Then i did a complete fresh install of cursor BUT didnt click any option so the installer didnt add the PATH variables for me (+code button and +cursor button).

Started cursor imported my VSCode settings (install WSL extension if it doesnt import from VSCode and/or u had not a WSL extension in your VSCode installation)

Now reloaded Cursor, connected with WSL and made sure `~/.cursor-server/bin/<your hash>/` was created at this point. (U need <your hash> for the next steps.)

Closed cursor.

Then i did the steps like described in this comment https://github.com/getcursor/cursor/issues/807#issuecomment-1728885825

Here comes the important part:
-  i replaced the COMMIT variable from the gist with `COMMIT=<your hash>` 
- changed `APP_NAME="code"` to `APP_NAME="cursor"` 
- replaced VSCODE_PATH with `VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"` like mentioned here already a many times. 

Saved the file.

In the text editor where i kept the copied content from `printenv PATH USER` i added to the end of the Variables `:/mnt/c/Users/<your user>/AppData/Local/Programs/cursor/resources/app/bin` should be the same for  the most. copied my new version and added it to my PATH variabled with `PATH="<copied new version>"` in a WSL Terminal. 

It is important that the variable in PATH for cursor has to be after the one from VSCode, or it will override the script from VSCode because it contains a script named "code" as well...

sorry for all the Typos and bad grammar

**Comment by angga7togk** [comment]
I have provided a tutorial in my repository, please check it
[https://github.com/angga7togk/command-cursor-editor-linux](https://github.com/angga7togk/command-cursor-editor-linux)

**Comment by SC7639** [comment]
This is still an issue and this is the only reliable fix I've found

> It's unbelievable this is still broken after so many months, and the fix is rather simple. Sadly Cursor is not open source... but here's a quick workaround based on VS Code's current launcher from WSL:
> 
> Caution
> 
> This will most likely break after Cursor gets an update. Hopefully they'll fix this in the next update, but if not these tweaks may need to be done again after every update.
> 
> Note
> 
> You should install the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) before attempting these steps
> 
> Important
> 
> I opened a WSL folder at least once before doing these steps. Doing so installed Cursor's WSL Server in `~/.cursor-server/bin`. I'm not sure if this altered VS Code script would trigger that too if you directly run `cursor` without the WSL Server installed.
> 
> 1. Open the `cursor` linux script
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\cursor\resources\app\bin\`
>    * If you've installed the `cursor` command you can also:
>      
>      * Use `which` in WSL:
>        ```
>        $ which cursor
>        /mnt/c/Users/lesmo/AppData/Local/Programs/cursor/resources/app/bin/cursor
>        ```
>      * Use `where` in Windows' Command Prompt:
>        ```
>        > where cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor.cmd
>        ```
>      * Use `(Get-Command cursor).Source` in PowerShell :
>        ```
>        > (Get-Command code).Source
>        C:\Users\lesmo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
>        ```
> 2. Copy the `code` linux script contents into the `cursor` one
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\Microsoft VS Code\bin\`
> 3. Patch the script with:
>    
>    * Cursor values for the variables:
>      
>      * `COMMIT` should have the value of the binary under `~/.cursor-server/bin`, which for me right now is `56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10`
>      * `APP_NAME` should be `"cursor"`
>      * `NAME` should be `"Cursor"`
>      * `SERVERDATAFOLDER` should be `".cursor-server"`
>      * `VSCODE_PATH` should be `"$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"`
>        
>        * _Paths slightly differ from VS Code, so this extra `dirname` calls are necessary)_
>    * Fix the semi-invalid output from the call to Cursor as CLI in line 47
>      
>      * The `cat /tmp/remote-wsl-loc.txt` expects to only output a path, but it outputs 2 lines that breaks the script. To fix this, we forcibly get only the 2nd line:
>        ```shell
>        WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
>        ```
> 
> Cursor will now be correctly launched by whatever WSL instance invokes it:
> 
>  20240219_014531.mp4 
> This is my current `cursor` file contents:
> 
> ```shell
> #!/usr/bin/env sh
> #
> # Copyright (c) Microsoft Corporation. All rights reserved.
> # Licensed under the MIT License. See License.txt in the project root for license information.
> if [ "$VSCODE_WSL_DEBUG_INFO" = true ]; then
> 	set -x
> fi
> 
> COMMIT="56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10"
> APP_NAME="cursor"
> QUALITY="stable"
> NAME="Cursor"
> SERVERDATAFOLDER=".cursor-server"
> VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
> ELECTRON="$VSCODE_PATH/$NAME.exe"
> 
> IN_WSL=false
> if [ -n "$WSL_DISTRO_NAME" ]; then
> 	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
> 	IN_WSL=true
> else
> 	WSL_BUILD=$(uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft.*|.*/\1/')
> 	if [ -n "$WSL_BUILD" ]; then
> 		if [ "$WSL_BUILD" -ge 17063 ]; then
> 			# WSLPATH is available since WSL build 17046
> 			# WSLENV is available since WSL build 17063
> 			IN_WSL=true
> 		else
> 			# If running under older WSL, don't pass cli.js to Electron as
> 			# environment vars cannot be transferred from WSL to Windows
> 			# See: https://github.com/microsoft/BashOnWindows/issues/1363
> 			#      https://github.com/microsoft/BashOnWindows/issues/1494
> 			"$ELECTRON" "$@"
> 			exit $?
> 		fi
> 	fi
> fi
> if [ $IN_WSL = true ]; then
> 
> 	export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
> 	CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> 
> 	# use the Remote WSL extension if installed
> 	WSL_EXT_ID="ms-vscode-remote.remote-wsl"
> 
> 	ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID >/tmp/remote-wsl-loc.txt 2>/dev/null </dev/null
> 	WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
> 
> 	if [ -n "$WSL_EXT_WLOC" ]; then
> 		# replace \r\n with \n in WSL_EXT_WLOC
> 		WSL_CODE=$(wslpath -u "${WSL_EXT_WLOC%%[[:cntrl:]]}")/scripts/wslCode.sh
> 		"$WSL_CODE" "$COMMIT" "$QUALITY" "$ELECTRON" "$APP_NAME" "$SERVERDATAFOLDER" "$@"
> 		exit $?
> 	fi
> 
> elif [ -x "$(command -v cygpath)" ]; then
> 	CLI=$(cygpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> else
> 	CLI="$VSCODE_PATH/resources/app/out/cli.js"
> fi
> ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
> exit $?
> ```
> 
> P.S.: Cursor ppl, hire me? lol

**Comment by Mayurifag** [comment]
Problem still exists

**Comment by OmarNaguib** [comment]
> It's unbelievable this is still broken after so many months, and the fix is rather simple. Sadly Cursor is not open source... but here's a quick workaround based on VS Code's current launcher from WSL:
> 
> Caution
> 
> This will most likely break after Cursor gets an update. Hopefully they'll fix this in the next update, but if not these tweaks may need to be done again after every update.
> 
> Note
> 
> You should install the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) before attempting these steps
> 
> Important
> 
> I opened a WSL folder at least once before doing these steps. Doing so installed Cursor's WSL Server in `~/.cursor-server/bin`. I'm not sure if this altered VS Code script would trigger that too if you directly run `cursor` without the WSL Server installed.
> 
> 1. Open the `cursor` linux script
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\cursor\resources\app\bin\`
>    * If you've installed the `cursor` command you can also:
>      
>      * Use `which` in WSL:
>        ```
>        $ which cursor
>        /mnt/c/Users/lesmo/AppData/Local/Programs/cursor/resources/app/bin/cursor
>        ```
>      * Use `where` in Windows' Command Prompt:
>        ```
>        > where cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor.cmd
>        ```
>      * Use `(Get-Command cursor).Source` in PowerShell :
>        ```
>        > (Get-Command code).Source
>        C:\Users\lesmo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
>        ```
> 2. Copy the `code` linux script contents into the `cursor` one
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\Microsoft VS Code\bin\`
> 3. Patch the script with:
>    
>    * Cursor values for the variables:
>      
>      * `COMMIT` should have the value of the binary under `~/.cursor-server/bin`, which for me right now is `56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10`
>      * `APP_NAME` should be `"cursor"`
>      * `NAME` should be `"Cursor"`
>      * `SERVERDATAFOLDER` should be `".cursor-server"`
>      * `VSCODE_PATH` should be `"$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"`
>        
>        * _Paths slightly differ from VS Code, so this extra `dirname` calls are necessary)_
>    * Fix the semi-invalid output from the call to Cursor as CLI in line 47
>      
>      * The `cat /tmp/remote-wsl-loc.txt` expects to only output a path, but it outputs 2 lines that breaks the script. To fix this, we forcibly get only the 2nd line:
>        ```shell
>        WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
>        ```
> 
> Cursor will now be correctly launched by whatever WSL instance invokes it:
> 
>  20240219_014531.mp4 
> This is my current `cursor` file contents:
> 
> ```shell
> #!/usr/bin/env sh
> #
> # Copyright (c) Microsoft Corporation. All rights reserved.
> # Licensed under the MIT License. See License.txt in the project root for license information.
> if [ "$VSCODE_WSL_DEBUG_INFO" = true ]; then
> 	set -x
> fi
> 
> COMMIT="56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10"
> APP_NAME="cursor"
> QUALITY="stable"
> NAME="Cursor"
> SERVERDATAFOLDER=".cursor-server"
> VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
> ELECTRON="$VSCODE_PATH/$NAME.exe"
> 
> IN_WSL=false
> if [ -n "$WSL_DISTRO_NAME" ]; then
> 	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
> 	IN_WSL=true
> else
> 	WSL_BUILD=$(uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft.*|.*/\1/')
> 	if [ -n "$WSL_BUILD" ]; then
> 		if [ "$WSL_BUILD" -ge 17063 ]; then
> 			# WSLPATH is available since WSL build 17046
> 			# WSLENV is available since WSL build 17063
> 			IN_WSL=true
> 		else
> 			# If running under older WSL, don't pass cli.js to Electron as
> 			# environment vars cannot be transferred from WSL to Windows
> 			# See: https://github.com/microsoft/BashOnWindows/issues/1363
> 			#      https://github.com/microsoft/BashOnWindows/issues/1494
> 			"$ELECTRON" "$@"
> 			exit $?
> 		fi
> 	fi
> fi
> if [ $IN_WSL = true ]; then
> 
> 	export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
> 	CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> 
> 	# use the Remote WSL extension if installed
> 	WSL_EXT_ID="ms-vscode-remote.remote-wsl"
> 
> 	ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID >/tmp/remote-wsl-loc.txt 2>/dev/null </dev/null
> 	WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
> 
> 	if [ -n "$WSL_EXT_WLOC" ]; then
> 		# replace \r\n with \n in WSL_EXT_WLOC
> 		WSL_CODE=$(wslpath -u "${WSL_EXT_WLOC%%[[:cntrl:]]}")/scripts/wslCode.sh
> 		"$WSL_CODE" "$COMMIT" "$QUALITY" "$ELECTRON" "$APP_NAME" "$SERVERDATAFOLDER" "$@"
> 		exit $?
> 	fi
> 
> elif [ -x "$(command -v cygpath)" ]; then
> 	CLI=$(cygpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> else
> 	CLI="$VSCODE_PATH/resources/app/out/cli.js"
> fi
> ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
> exit $?
> ```
> 
> P.S.: Cursor ppl, hire me? lol

This is amazing! Thanks

can i ask you about your background and how you were able to debug this?

**Comment by Allengl** [comment]
> It's unbelievable this is still broken after so many months, and the fix is rather simple. Sadly Cursor is not open source... but here's a quick workaround based on VS Code's current launcher from WSL:
> 
> Caution
> 
> This will most likely break after Cursor gets an update. Hopefully they'll fix this in the next update, but if not these tweaks may need to be done again after every update.
> 
> Note
> 
> You should install the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) before attempting these steps
> 
> Important
> 
> I opened a WSL folder at least once before doing these steps. Doing so installed Cursor's WSL Server in `~/.cursor-server/bin`. I'm not sure if this altered VS Code script would trigger that too if you directly run `cursor` without the WSL Server installed.
> 
> 1. Open the `cursor` linux script
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\cursor\resources\app\bin\`
>    * If you've installed the `cursor` command you can also:
>      
>      * Use `which` in WSL:
>        ```
>        $ which cursor
>        /mnt/c/Users/lesmo/AppData/Local/Programs/cursor/resources/app/bin/cursor
>        ```
>      * Use `where` in Windows' Command Prompt:
>        ```
>        > where cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor.cmd
>        ```
>      * Use `(Get-Command cursor).Source` in PowerShell :
>        ```
>        > (Get-Command code).Source
>        C:\Users\lesmo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
>        ```
> 2. Copy the `code` linux script contents into the `cursor` one
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\Microsoft VS Code\bin\`
> 3. Patch the script with:
>    
>    * Cursor values for the variables:
>      
>      * `COMMIT` should have the value of the binary under `~/.cursor-server/bin`, which for me right now is `56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10`
>      * `APP_NAME` should be `"cursor"`
>      * `NAME` should be `"Cursor"`
>      * `SERVERDATAFOLDER` should be `".cursor-server"`
>      * `VSCODE_PATH` should be `"$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"`
>        
>        * _Paths slightly differ from VS Code, so this extra `dirname` calls are necessary)_
>    * Fix the semi-invalid output from the call to Cursor as CLI in line 47
>      
>      * The `cat /tmp/remote-wsl-loc.txt` expects to only output a path, but it outputs 2 lines that breaks the script. To fix this, we forcibly get only the 2nd line:
>        ```shell
>        WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
>        ```
> 
> Cursor will now be correctly launched by whatever WSL instance invokes it:
> 
>  20240219_014531.mp4 
> This is my current `cursor` file contents:
> 
> ```shell
> #!/usr/bin/env sh
> #
> # Copyright (c) Microsoft Corporation. All rights reserved.
> # Licensed under the MIT License. See License.txt in the project root for license information.
> if [ "$VSCODE_WSL_DEBUG_INFO" = true ]; then
> 	set -x
> fi
> 
> COMMIT="56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10"
> APP_NAME="cursor"
> QUALITY="stable"
> NAME="Cursor"
> SERVERDATAFOLDER=".cursor-server"
> VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
> ELECTRON="$VSCODE_PATH/$NAME.exe"
> 
> IN_WSL=false
> if [ -n "$WSL_DISTRO_NAME" ]; then
> 	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
> 	IN_WSL=true
> else
> 	WSL_BUILD=$(uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft.*|.*/\1/')
> 	if [ -n "$WSL_BUILD" ]; then
> 		if [ "$WSL_BUILD" -ge 17063 ]; then
> 			# WSLPATH is available since WSL build 17046
> 			# WSLENV is available since WSL build 17063
> 			IN_WSL=true
> 		else
> 			# If running under older WSL, don't pass cli.js to Electron as
> 			# environment vars cannot be transferred from WSL to Windows
> 			# See: https://github.com/microsoft/BashOnWindows/issues/1363
> 			#      https://github.com/microsoft/BashOnWindows/issues/1494
> 			"$ELECTRON" "$@"
> 			exit $?
> 		fi
> 	fi
> fi
> if [ $IN_WSL = true ]; then
> 
> 	export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
> 	CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> 
> 	# use the Remote WSL extension if installed
> 	WSL_EXT_ID="ms-vscode-remote.remote-wsl"
> 
> 	ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID >/tmp/remote-wsl-loc.txt 2>/dev/null </dev/null
> 	WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
> 
> 	if [ -n "$WSL_EXT_WLOC" ]; then
> 		# replace \r\n with \n in WSL_EXT_WLOC
> 		WSL_CODE=$(wslpath -u "${WSL_EXT_WLOC%%[[:cntrl:]]}")/scripts/wslCode.sh
> 		"$WSL_CODE" "$COMMIT" "$QUALITY" "$ELECTRON" "$APP_NAME" "$SERVERDATAFOLDER" "$@"
> 		exit $?
> 	fi
> 
> elif [ -x "$(command -v cygpath)" ]; then
> 	CLI=$(cygpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> else
> 	CLI="$VSCODE_PATH/resources/app/out/cli.js"
> fi
> ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
> exit $?
> ```
> 
> P.S.: Cursor ppl, hire me? lol

working for me thanks !!!

**Comment by bilalbayasut** [comment]
got
```bash
/mnt/c/Users/xxx/.cursor/extensions/ms-vscode-remote.remote-wsl-0.81.8/scripts/wslCode.sh: 63: /home/xxx/.cursor-server/bin/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/bin/remote-cli/cursor: not found
```

**Comment by corticalstack** [comment]
I wish I had seen this before uninstalling vanilla vscode to get cursor up and running in WSL, uggh.

**Comment by xantorres** [comment]
Unacceptable bug, removed the app until this is fixed

**Comment by lesmo** [comment]
🤣 can't believe this is still broken after almost a year now

> This is amazing! Thanks
> 
> can i ask you about your background and how you were able to debug this? @lesmo

@OmarNaguib just a software engineer, been doing this for a decade now... debugging is just like everything else: just follow the error messages and tweak things 'til it works 🤷‍♂️

**Comment by joacoesperon** [comment]
> It's unbelievable this is still broken after so many months, and the fix is rather simple. Sadly Cursor is not open source... but here's a quick workaround based on VS Code's current launcher from WSL:
> 
> Caution
> 
> This will most likely break after Cursor gets an update. Hopefully they'll fix this in the next update, but if not these tweaks may need to be done again after every update.
> 
> Note
> 
> You should install the [WSL Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) before attempting these steps
> 
> Important
> 
> I opened a WSL folder at least once before doing these steps. Doing so installed Cursor's WSL Server in `~/.cursor-server/bin`. I'm not sure if this altered VS Code script would trigger that too if you directly run `cursor` without the WSL Server installed.
> 
> 1. Open the `cursor` linux script
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\cursor\resources\app\bin\`
>    * If you've installed the `cursor` command you can also:
>      
>      * Use `which` in WSL:
>        ```
>        $ which cursor
>        /mnt/c/Users/lesmo/AppData/Local/Programs/cursor/resources/app/bin/cursor
>        ```
>      * Use `where` in Windows' Command Prompt:
>        ```
>        > where cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor
>        c:\Users\lesmo\AppData\Local\Programs\cursor\resources\app\bin\cursor.cmd
>        ```
>      * Use `(Get-Command cursor).Source` in PowerShell :
>        ```
>        > (Get-Command code).Source
>        C:\Users\lesmo\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
>        ```
> 2. Copy the `code` linux script contents into the `cursor` one
>    
>    * Most likely located at `C:\Users\<your user>\AppData\Local\Programs\Microsoft VS Code\bin\`
> 3. Patch the script with:
>    
>    * Cursor values for the variables:
>      
>      * `COMMIT` should have the value of the binary under `~/.cursor-server/bin`, which for me right now is `56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10`
>      * `APP_NAME` should be `"cursor"`
>      * `NAME` should be `"Cursor"`
>      * `SERVERDATAFOLDER` should be `".cursor-server"`
>      * `VSCODE_PATH` should be `"$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"`
>        
>        * _Paths slightly differ from VS Code, so this extra `dirname` calls are necessary)_
>    * Fix the semi-invalid output from the call to Cursor as CLI in line 47
>      
>      * The `cat /tmp/remote-wsl-loc.txt` expects to only output a path, but it outputs 2 lines that breaks the script. To fix this, we forcibly get only the 2nd line:
>        ```shell
>        WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
>        ```
> 
> Cursor will now be correctly launched by whatever WSL instance invokes it:
> 
>  20240219_014531.mp4 
> This is my current `cursor` file contents:
> 
> ```shell
> #!/usr/bin/env sh
> #
> # Copyright (c) Microsoft Corporation. All rights reserved.
> # Licensed under the MIT License. See License.txt in the project root for license information.
> if [ "$VSCODE_WSL_DEBUG_INFO" = true ]; then
> 	set -x
> fi
> 
> COMMIT="56becd74fc3058ee97a0b2496d8ae7ad2c2fcb10"
> APP_NAME="cursor"
> QUALITY="stable"
> NAME="Cursor"
> SERVERDATAFOLDER=".cursor-server"
> VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
> ELECTRON="$VSCODE_PATH/$NAME.exe"
> 
> IN_WSL=false
> if [ -n "$WSL_DISTRO_NAME" ]; then
> 	# $WSL_DISTRO_NAME is available since WSL builds 18362, also for WSL2
> 	IN_WSL=true
> else
> 	WSL_BUILD=$(uname -r | sed -E 's/^[0-9.]+-([0-9]+)-Microsoft.*|.*/\1/')
> 	if [ -n "$WSL_BUILD" ]; then
> 		if [ "$WSL_BUILD" -ge 17063 ]; then
> 			# WSLPATH is available since WSL build 17046
> 			# WSLENV is available since WSL build 17063
> 			IN_WSL=true
> 		else
> 			# If running under older WSL, don't pass cli.js to Electron as
> 			# environment vars cannot be transferred from WSL to Windows
> 			# See: https://github.com/microsoft/BashOnWindows/issues/1363
> 			#      https://github.com/microsoft/BashOnWindows/issues/1494
> 			"$ELECTRON" "$@"
> 			exit $?
> 		fi
> 	fi
> fi
> if [ $IN_WSL = true ]; then
> 
> 	export WSLENV="ELECTRON_RUN_AS_NODE/w:$WSLENV"
> 	CLI=$(wslpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> 
> 	# use the Remote WSL extension if installed
> 	WSL_EXT_ID="ms-vscode-remote.remote-wsl"
> 
> 	ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID >/tmp/remote-wsl-loc.txt 2>/dev/null </dev/null
> 	WSL_EXT_WLOC=$(cat /tmp/remote-wsl-loc.txt | head -2 | tail -1)
> 
> 	if [ -n "$WSL_EXT_WLOC" ]; then
> 		# replace \r\n with \n in WSL_EXT_WLOC
> 		WSL_CODE=$(wslpath -u "${WSL_EXT_WLOC%%[[:cntrl:]]}")/scripts/wslCode.sh
> 		"$WSL_CODE" "$COMMIT" "$QUALITY" "$ELECTRON" "$APP_NAME" "$SERVERDATAFOLDER" "$@"
> 		exit $?
> 	fi
> 
> elif [ -x "$(command -v cygpath)" ]; then
> 	CLI=$(cygpath -m "$VSCODE_PATH/resources/app/out/cli.js")
> else
> 	CLI="$VSCODE_PATH/resources/app/out/cli.js"
> fi
> ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
> exit $?
> ```
> 
> P.S.: Cursor ppl, hire me? lol



you are the GOAT

**Comment by joacoesperon** [comment]
Worked for me, thanks

**Comment by TexasCoding** [comment]
> You can try this:
> 
> 1. Open cursor, and connect to wsl
> 2. Then run this `fixWSL.sh` in the wsl
> 
> ```shell
> #!/usr/bin/env bash
> 
> # Function to backup a file if it exists
> backup_file() {
>     local file_path=$1
>     if [ -e "$file_path" ]; then
>         mv "$file_path" "$file_path.bak"
>     fi
> }
> 
> # Function to safely copy a file and create a backup if it doesn't exist
> safe_copy_with_backup() {
>     local src=$1
>     local dest=$2
>     cp "$src" "$dest"
>     if [ ! -e "$dest.bak" ]; then
>         cp "$dest" "$dest.bak"
>     fi
> }
> 
> # Function to perform the sed replacements
> perform_replacements() {
>     local file_path=$1
>     local bin_path=$2
> 
>     sed -i 's|APP_NAME="code"|APP_NAME="cursor"|' "$file_path"
>     if [ -n "$bin_path" ]; then
>         local commit
>         commit=$(basename "$bin_path")
>         sed -i "s|COMMIT=\"[^\"]*\"|COMMIT=\"$commit\"|" "$file_path"
>     fi
>     sed -i 's|NAME="Code"|NAME="Cursor"|' "$file_path"
>     sed -i 's|SERVERDATAFOLDER=".vscode-server"|SERVERDATAFOLDER=".cursor-server"|' "$file_path"
>     sed -i -E 's|VSCODE_PATH=".+"|VSCODE_PATH="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"|' "$file_path"
>     sed -i -E 's|WSL_EXT_WLOC=(.+)|WSL_EXT_WLOC=$(tail -1 /tmp/remote-wsl-loc.txt)|' "$file_path"
> }
> 
> # Main script execution
> CODE_PATH=$(which code)
> if [[ "$CODE_PATH" == *"cursor"* ]]; then
>     backup_file "$CODE_PATH"
> fi
> 
> CODE_WIN_PATH=$(which code)
> CURSOR_WIN_PATH=$(which cursor)
> BIN_PATH=$(ls -d ~/.cursor-server/bin/*/ 2>/dev/null | head -n 1)
> 
> safe_copy_with_backup "$CODE_WIN_PATH" "$CURSOR_WIN_PATH"
> perform_replacements "$CURSOR_WIN_PATH" "$BIN_PATH"
> ```

Fixed it perfectly. Thanks for the easy fix

**Comment by akshay-nm** [comment]
thank you for breaking my dev setup 
wasted my 20 mins 
not using cursor

**Comment by tmm1** [comment]
This issue should be fixed in today's 0.41.1 release!

**Comment by parkerjgit** [comment]
> This issue should be fixed in today's 0.41.1 release!

0.41.2. not fixed for me. `cursor: attempt update` doesn't do anything...

**Comment by NVS-AI** [comment]
This is still not fixed as of 0.42.2 Unbelievable!

**Comment by juanrd99** [comment]
2025: Still breaking, solutions on the discussion work, but it should be fixed

**Comment by LiarCoder** [comment]
After I install Cursor, `cursor` command doesn't work in my `git-bash` terminal. And I notice that `code` command doesn't work, either!

```bash
$ cursor .
/c/Users/xx/AppData/Local/Programs/cursor/resources/app/bin/cursor: line 61: /c/Users/xx/AppData/Local/Programs/cursor/Cursor.exe: Permission denied

$ code .
/c/Users/xx/AppData/Local/Programs/cursor/resources/app/bin/code: line 61: /c/Users/xx/AppData/Local/Programs/cursor/Cursor.exe: Permission denied
```

And I found that there is a executable file named `code` in ther `/c/Users/xx/AppData/Local/Programs/cursor/resources/app/bin` directory（I called it `cursor directory`）.

Then I checked my `PATH` environment variable，and I found `cursor directory` just in front of `D:\Editor\VSCode\bin`（I I called it `vscode directory`） where my `code` command was placed.

![Image](https://github.com/user-attachments/assets/1444b5ea-3045-4b73-a0b5-d54c30f7b82b)

So, I guess the `code` command in the `cursor directory` has higher priority then the one in the `vscode directory`. I was overridden!

So, I exchange the position of those two directory, and I tired `code` command in `git-bash` again，I works!🎉

**Comment by ShepSims** [comment]
Simple solution 

add 

alias cursor='open -a Cursor'

to whatever path file you have 

on Mac by default I use zsh so my ~/.zprofile looks like this now

eval "$(/opt/homebrew/bin/brew shellenv)"
alias cursor='open -a Cursor'

  - and it works!

**Comment by naourass** [comment]
I've installed the "cursor" version for the command line, but now calling "code" command opens cursor too. Any parameter to fix this?

**Comment by martijn10kb** [comment]
Yes, but keep this page in your bookmarks, this will be undone with any major update..
