### ISSUE TITLE
Cursor Theme text is not correctly highlighting.

### ISSUE THREAD

**Issue by jjfantini** [getcursor/cursor#945]
OS: Windows 11

I have `Dark Modern` theme activated on my VSCode app, and I have the same theme in cursor. I have the same extensions for each app, but the text syntax highlighting is different for the themes between VSCode and Cursos. This should be the same, and there is much more helpful coloring in VSCode.

## VSCode Text:
- docstring color is red
- constants color is blue
- classes and package color is green
- function color is yellow
- comments are green
![txt-vscode](https://github.com/getcursor/cursor/assets/63276164/442288d9-f5d3-4f9e-8465-d5715b7664fc)

## Cursor Text:
- docstring color is green
- constants color is white
- classes and package color is white
- function color is white
- comments are green
![txt-cursor](https://github.com/getcursor/cursor/assets/63276164/497f4ca1-766f-4c5f-a791-8be2f93be3f4)

It should be that the same themes have the same syntax highlighting to improve compatibility in workflows for devs. This along with #841, prevents me from full conversion. I have to have both IDE's open in order to have the same functionality, which I end up just using Cursos for codebase questions and code creation and VScode for the rest.

**Comment by Luzzotica** [comment]
I am having the same issue with GDScript syntax highlighting from the `godot-tools` package.

**Comment by truell20** [comment]
Likely an issue with Pylance. We just pushed a fix for this. Do you still see issues after upgrading?

**Comment by jjfantini** [comment]
IS there an easy way to see what Cursor version I am running? Cant seem to find in settings anywhere. It would be really convenient to have a menu to manage Cursor versions and updates form within the app itself. @truell20

**Comment by jjfantini** [comment]
I have reopened my Cursor app, not sure if it includes the latest update. I am still seeing the same issue with Intellicode Error.
@truell20

**Comment by jjfantini** [comment]
Restated my Cursor app again, and now the text highlighting has been fixed and Pylance is working correctly! Thanks for the quick hotfix! @truell20

**Comment by jjfantini** [comment]
It is very slow however, changes in the codebase take a long time to highlight the syntax. Even after saving the file

**Comment by Luzzotica** [comment]
I have upgraded, but am still not seeing any synytax highlighting using Dark (Visual Studio) theme.

Here is the info on Cursor from the about section:

Version: 0.11.5
VSCode Version: 1.80.1
Commit: 598d3e09a76d6c7f9e541c04c5e5df113aeb0b70
Date: 2023-09-22T01:52:26.146Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0

**Comment by jjfantini** [comment]
I am using conda python interpreter, and still not seeing any text syntax coloring, Pylance is installed.

OS: WIndows 11

![syntax-error](https://github.com/getcursor/cursor/assets/63276164/e8aef07e-3e6d-407c-866f-a5ed7f884968)

**Comment by jjfantini** [comment]
It works for the most part, but randomly stops working in the middle of a dev session, and reloading the widnwo seems to clear it up for the next little bit

**Comment by olivieropinotti** [comment]
Hi there! I'm still having this issue on Python, I tried changing interpreters but with no success, can somebody help?

**Comment by arkaydeus** [comment]
I'm still having this issue too and it's really annoying

<img width="347" alt="image" src="https://github.com/user-attachments/assets/c179e0d0-6bab-4ab1-8de4-f27630a6d87f">

Some old text correctly highlighted, new text is not.

**Comment by gp48maz1** [comment]
Was this resolved I have this issue as well -- if not any other work arounds?

**Comment by gp48maz1** [comment]
Quick note to anyone else who comes to this thread... restarting will fix your issue -- or at least that worked for me

**Comment by anuin-cat** [comment]
You can install the extension： < Kylin Python(with jedi language server) > and < Pylint > to replace < python > and < pylance > to resolve this issue.

**Comment by flyte** [comment]
I had to change my colour scheme to Dark Modern instead of Dark (Visual Studio) for it to work.

**Comment by damanc7** [comment]
Still an issue in Cursor Version: 0.45.5. Changing color scheme like @flyte and installing pylance worked

**Comment by ludzerr** [comment]
Hello, I still have the same issue, I tried everything that you guys discussed about to fix it but still the same result...

**Comment by sitloboi2012** [comment]
hi team any update on this one ?

**Comment by ycjcl868** [comment]
I still have the same issue


<img width="696" alt="Image" src="https://github.com/user-attachments/assets/82714ef0-da42-4308-8015-0eb51f91fb3e" />

**Comment by SishaarRao** [comment]
![Image](https://github.com/user-attachments/assets/21dc8a44-e3ce-439b-afba-0ceaa010dfbf)
Seeing an issue where even in the same word there are different colors. This seems to have broken recently, was fine a week or two ago. Anybody know how to downgrade?

**Comment by Edenzzzz** [comment]
Could you fix this please @truell20 @Sanger2000 @terror @sunray-ley

**Comment by arkaydeus** [comment]
In the end I fixed it by following the steps here:

https://substack.com/home/post/p-158197171

**Comment by caisarl76** [comment]
https://substack.com/home/post/p-158197171

I solved through this solution! FYI
